fitsio-sys/Cargo.toml, fitsio-sys/build.rs
=> Probe system for custom cfitsio location

fitsio/src/columndescription.rs, fitsio/src/fitserror.rs, fitsio/src/fitsfile.rs, fitsio/src/fitshdu.rs, fitsio/src/lib.rs, fitsio/src/types.rs
=> Merge hdu types

fitsio/CHANGELOG.md, fitsio/src/errors.rs, fitsio/src/fitserror.rs, fitsio/src/fitsfile.rs, fitsio/src/lib.rs, fitsio/tests/test_ushort.rs, test_all.sh
WIP, see #39
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/40)
=> Rearchitect pass fitsfile

CHANGELOG.md, CONTRIBUTING.md, fitsio/src/fitsfile.rs, fitsio/src/lib.rs
Adds the ability to insert, append and delete columns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/43)
=> Add column impl

fitsio/src/fitsfile.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/44)
=> Add method to copy hdu to new file

fitsio/src/fitsfile.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/46)
=> Add ability to iterate over hdus

fitsio/src/fitsfile.rs
Attempt to fix #29 through use of proper rust CStrings rather than my hacky way of storing a vector of pointers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/48)
=> Fix bug by building CStrings

fitsio/src/fitsfile.rs, fitsio/src/lib.rs
Use the builder pattern to allow for custom primary HDU
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/53)
=> Enable the user to customise the primary HDU

README.md
See #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/58)
=> Add version of cfitsio to readme

CHANGELOG.md, fitsio/src/fitsfile.rs, fitsio/src/lib.rs
Make sure the range arguments are consistent with each other, and exclusive of the upper value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/61)
=> Exclusive ranges

bin/test, fitsio/examples/full_example.rs, fitsio/src/lib.rs
See #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/75)
=> Add meaningful example

CHANGELOG.md, CONTRIBUTING.md, fitsio/examples/full_example.rs, fitsio/src/fitsfile.rs, fitsio/src/lib.rs
See #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/77)
=> Add `primary_hdu` method

fitsio/src/columndescription.rs, fitsio/src/fitsfile.rs, fitsio/src/stringutils.rs, fitsio/src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/78)
=> All tests begin with test_

fitsio/src/fitsfile.rs
See #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/79)
=> Hides all trait docs

CHANGELOG.md, fitsio/examples/full_example.rs, fitsio/src/fitsfile.rs
See #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/80)
=> WritesKey accepts &str and String

CHANGELOG.md, fitsio/examples/full_example.rs, fitsio/src/fitsfile.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/81)
=> `create_` methods take `Into<String>`

fitsio/examples/full_example.rs, fitsio/src/fitsfile.rs
See #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/82)
=> Take AsRef<Path> when creating/opening fits file

CHANGELOG.md, fitsio/examples/full_example.rs, fitsio/src/bin/fitssummary.rs, fitsio/src/errors.rs, fitsio/src/fitserror.rs, fitsio/src/fitsfile.rs
See #73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/83)
=> Add pretty printing support

CHANGELOG.md, fitsio/examples/full_example.rs, fitsio/src/fitsfile.rs, fitsio/src/lib.rs, fitsio/src/types.rs, fitsio/tests/test_ushort.rs
See #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/84)
=> More rusty data type for image description

fitsio/src/lib.rs
See #70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/85)
=> Add documentation for write_image

CHANGELOG.md, fitsio/Cargo.toml, fitsio/benches/benchmarks.rs, fitsio/src/hdu.rs, fitsio/src/longnam.rs
In the future we may want to benchmark functions. This adds `criterion.rs` to enable more detailed benchmarks in the future.
=> Add benchmarks

.travis.yml, bin/run_sanitizers.sh, fitsio/src/fitsfile.rs, fitsio/src/hdu.rs, fitsio/src/headers.rs, fitsio/src/stringutils.rs, fitsio/src/tables.rs
Attempt to run sanitizers (rust-san and miri) in CI
=> Miri sanitizer ci

fitsio/src/fitsfile.rs, fitsio/src/hdu.rs
Hi again, just a tweak this time.  This will help some error messages I'm developing in my own code.  Let me know if there should be more added with this change.
=> Make the HDU number public.

.github/workflows/test.yml, fitsio-sys/Cargo.toml, shell.nix
Start to ensure that minimal crate versions in `Cargo.toml` still work
Closes #186
=> Minimal version tests

.github/workflows/check.yml, .github/workflows/schedule.yml, .github/workflows/test.yml, README.md, bin/test, fitsio/Cargo.toml, fitsio/src/fitsfile.rs, fitsio/src/tables.rs
Determine and document the minimum supported Rust version (MSRV) for our users.
This change also includes a test that tests the project using the MSRV so that we know when failures occur.
=> feat: get and doc MSRV of 1.57.0

CHANGELOG.md, README.md, fitsio-sys-bindgen/Cargo.toml, fitsio-sys-bindgen/build.rs, fitsio-sys/Cargo.toml, fitsio-sys/build.rs, fitsio/Cargo.toml
=> fix: require specific cfitsio version

.github/workflows/test.yml
This PR implements basic windows CI support
Note: this will fail for a little while until #199 is integrated
=> Implement windows CI

.github/workflows/coverage.yml, README.md
- add coverage workflow (for main branch only)
- update coverage badge
=> Add coverage

.github/workflows/coverage.yml, fitsio/src/errors.rs, fitsio/src/images.rs, fitsio/src/tables.rs
I want to see the coverage graphs go up, so pick some easy wins and add some test coverage.
=> Add more tests to increase coverage

.dockerignore, .github/workflows/docker-test-image.yml, Cross.toml
We use a custom docker image to run the arm tests. We should update this image regularly.
=> Regularly build docker image

README.md, fitsio/Cargo.toml, fitsio/src/lib.rs
This is a release PR for version **0.21.2**.
**Use a merge commit.**
**To trigger builds initially, close and then immediately re-open this PR once.**
=> release: fitsio v0.21.2

.github/dependabot.yml
=> Update GitHub actions versions automatically

fitsio/src/headers.rs
=> Add u/i16 short types

flake.nix
These tools are useful while developing
=> chore: add cargo helpers

.github/codecov.yml, .github/workflows/coverage.yml
Try to capture coverage of integration tests
=> chore: use codecov

fitsio/src/fitsfile.rs, fitsio/src/lib.rs
=> set  public fitsio::fitfile::FitsFile::num_hdus function.
