simonrw/rust-fitsio

.travis.yml

There have been a lot of test failures due to a cfitsio bug with the filesystem. This PR is a test to see if that is fixed when running on the container infrastructure. Also this should speed up builds anyway.

Change travis build to run on container infrastructure

---

fitsio-sys/build.rs

If the `fitsio-sys` build script cannot find `cfitsio` with `pkg-config`, it throws a horrible message (see #10). This change handles this case by printing a slightly more friendly error message.
The implementation is a little hacky - I was just trying to follow the compiler's advice and hence may not be very idiomatic rust, but it works...

Handle missing cfitsio on pkg-config path

---

fitsio/src/fitsfile.rs

Get the code compiling on arm
This mostly involved changing any read/write operations involving the long data type to use the `_longlong` variant on arm.

Arm compilation

---

fitsio/src/fitsfile.rs
fitsio/src/lib.rs
fitsio/src/types.rs

Add the ability to resize a fits image

Resize image

---

fitsio-sys/build.rs
fitsio-sys/src/lib.rs
fitsio/src/columndescription.rs
fitsio/src/fitserror.rs
fitsio/src/fitsfile.rs
fitsio/src/stringutils.rs

If some functionality is not supplied by this library, and the user wants to use this in their own code, then they should be able to access the raw `fitsfile` object and use `fitsio_sys` to replace this missing functionality.
This is dangerous, and hence has been marked as `unsafe`.

Give the user access to the underlying `fitsio_sys::fitsfile` object

---

README.md
fitsio-sys-bindgen/build.rs
fitsio-sys-bindgen/src/lib.rs
fitsio-sys/src/lib.rs
fitsio/Cargo.toml
fitsio/src/fitsfile.rs
fitsio/src/lib.rs

Allow conditional compilation using compilation features
#33

Bindgen feature

---

fitsio/src/fitsfile.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/45)

Allow deletion of hdus

---

CHANGELOG.md
fitsio-sys-bindgen/build.rs
fitsio-sys/build.rs
fitsio-sys/src/lib.rs
fitsio/src/columndescription.rs
fitsio/src/fitserror.rs
fitsio/src/fitsfile.rs
fitsio/src/lib.rs

An example given on the [rust users forum](https://users.rust-lang.org/t/calling-all-rusty-astronomers/14099/10?u=srwalker101) shows that when defining the dimensions of new images, the array is treated in fortran order rather than C. See the [cfitsio documentation](https://heasarc.gsfc.nasa.gov/fitsio/c/c_user/node40.html):
> C programmers should note that the ordering of arrays in FITS files, and hence in all the CFITSIO calls, is more similar to the dimensionality of arrays in Fortran rather than C. For instance if a FITS image has NAXIS1 = 100 and NAXIS2 = 50, then a 2-D array just large enough to hold the image should be declared as array[50][100] and not as array[100][50].
Consider where else this may be the case, and fix them.
---
This change is [<img …

Use C calling convention where possible

---

CHANGELOG.md
fitsio-derive/Cargo.toml
fitsio-derive/README.md
fitsio-derive/src/lib.rs
fitsio/Cargo.toml
fitsio/examples/full_example.rs
fitsio/src/errors.rs
fitsio/src/fitsfile.rs
fitsio/src/lib.rs
fitsio/src/types.rs
fitsio/tests/test_custom_derive.rs

The API is not great (returning a HashMap). Ideally I'd like to allow the user
to define a custom struct with the names of the fields they want returned, and
for `fitsio` to extract that. However, my proc-macro-fu is not sufficient just
yet.
See #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindriot101/rust-fitsio/86)

Add ability to read single row from table

---

CHANGELOG.md
fitsio/examples/full_example.rs
fitsio/src/errors.rs
fitsio/src/fitsfile.rs

If a file already exists, then overwrite it.
See #93

Add overwrite method for new fits files

---

bin/test
fitsio/Cargo.toml
homepage/fitsioexample/Cargo.toml
homepage/fitsioexample/src/bin/ndarray_support.rs

@Findus32 showed compilation problems with the homepage example. See https://github.com/mindriot101/rust-fitsio/issues/102
The problem was caused by different versions of `ndarray`. `fitsio` specified 0.11.2, and implemented `ReadImage` for the 0.11.2 version of `ArrayD`, whereas the example did not specify the version of `ndarray` (i.e. `ndarray = "*"`). When @Findus32 did a fresh clone of the repo, it installed the latest version of `ndarray` i.e. 0.12.1.
It seems that implementing a trait for a different version of a struct (i.e. `ArrayD` version 0.11.2 vs `ArrayD` version 0.12.1) does not propagate to the newer version.
This might be quite annoying, if the version of `ndarray` is different between library code and user code.

Readimage not implemented for ndarray

---

CHANGELOG.md
README.md
fitsio/Cargo.toml
fitsio/src/fitsfile.rs
fitsio/src/hdu.rs
fitsio/src/headers.rs
fitsio/src/images.rs
fitsio/src/lib.rs
fitsio/src/tables.rs

This means the `fptr` pointer can never be null, which is a good
guarantee to have. On the other hand, we have to make all of the member
methods take `self` mutably (i.e. exclusive access).
I think this is probably a reasonable tradeoff as the fitsfile pointer
should be owned exclusively. Two concurrent alterations to the same
backed file should not happen.

Implement fitsfile fptr via ptr::NonNull

---

fitsio-sys-bindgen/Cargo.toml
fitsio-sys-bindgen/src/lib.rs
fitsio/Cargo.toml
fitsio/benches/benchmarks.rs
fitsio/examples/full_example.rs
fitsio/src/fitsfile.rs
fitsio/src/hdu.rs
fitsio/src/lib.rs
fitsio/src/testhelpers.rs

Replace the deprecated package `tempdir` with the new `tempfile` package, which supports the functionality that we require.

Replace tempdir with tempfile

---

.github/workflows/test.yml
Cargo.toml
bin/test
bin/test_basic
bin/test_bindgen
bin/test_book_examples
bin/test_feature_array
bin/test_feature_fitsio_src
bin/test_full_example
fitsio/src/ndarray_compat.rs

Use a rust workspace for the package. This means we can run simple test commands against the whole workspace, rather than the convoluted test script.

Use workspace

---

bin/test
fitsio-sys-bindgen/Cargo.toml
fitsio-sys-bindgen/build.rs

New laptop with non-standard install location means our build system has
to be better.

Fix non-standard include paths

---

CHANGELOG.md
fitsio-derive/Cargo.toml
fitsio-sys-bindgen/Cargo.toml
fitsio-sys/Cargo.toml
fitsio/Cargo.toml
homepage/fitsioexample/Cargo.toml

Hi @mindriot101, hope you're doing well.
I was inspired by a [post](https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277/2) this morning to see if my own crates were behaving with respect to the minimum versions specified for my dependencies.  Needless to say, they were not, but I wasn't the only one!  I've taken an axe to `rust-fitsio` and found what I think are its minimum requirements.  I think it's a pretty innocuous commit, but let me know if there are questions.  With these changes, people can confidently build with `rust-fitsio` knowing that its dependencies are as tightly defined as possible.
Commit message:
Attempting to build/test after running `cargo +nightly -Z
minimal-versions update` will fail, because the dependency versions are …

Specify required patch versions for all deps.

---

CHANGELOG.md
fitsio-sys-bindgen/Cargo.toml
fitsio/Cargo.toml
fitsio/src/fitsfile.rs
homepage/fitsioexample/Cargo.toml

Hi @mindriot101, me again. The first commit here should help keep dependabot quiet. It was my mistake to pull `libc` down to `0.1.*`; it should've always been something in `0.2.*`.
The second commit also pins us against the most-current version of `ndarray`.  In the `main` branch, the `>=0.8.0` range is not very different from what it used to be (`0`), but this commit solves an important problem; if a new version of `ndarray` (e.g. `0.16.0`) is released and a crate is using both `rust-fitsio` and `ndarray 0.15.*`, `cargo` will eagerly use `ndarray 0.16.0` for `rust-fitsio` and `0.15.*` otherwise, causing interoperability issues. This has caused me great pain in the past (not via `rust-fitsio`, mind you) but I've only relatively recently understood why.
Anyway, let me know what you think! …

Dep versions

---

CHANGELOG.md
fitsio-sys-bindgen/Cargo.toml

It seems just a version bump was required.
Looks like this PR: https://github.com/rust-lang/rust-bindgen/pull/2203
FIxes #173

fix: update bindgen in fitsio-sys-bindgen

---

fitsio-sys-bindgen/Cargo.toml
fitsio-sys-bindgen/build.rs
fitsio-sys/Cargo.toml
fitsio-sys/build.rs
fitsio/Cargo.toml

This is so we don't _have_ to assume the package is on the system path,
and we link to libraries in that location explicitly.
closes #182

fix: include system lib locations in link arguments

---

.github/workflows/check.yml
README.md
fitsio-sys-bindgen/build.rs
fitsio-sys/build.rs

Nightly was complaining that we weren't using variables in our strings. Now we are using captured identifiers in format strings[0], but that does mean bumping the MSRV to 1.58 but that is from January of this year so it is fine.
[0]: https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings

fix nightly errors

---

fitsio/examples/reading_from_memory.rs
fitsio/src/errors.rs
fitsio/src/fitsfile.rs
fitsio/src/lib.rs
fitsio/tests/test_from_raw.rs

Support creating fitsfiles from raw pointers

---

CHANGELOG.md
fitsio-sys-bindgen/build.rs
fitsio-sys/Cargo.toml
fitsio-sys/build.rs

Do not specify version of cfitsio on windows

---

.gitignore
fitsio-sys/Cargo.toml
fitsio-sys/build.rs

We can use the autotools crate to simplify the custom build script.
This is the first part in moving the `fitsio-sys-bindgen` crate inline with `fitsio-sys`.

use autotools crate for fitsio-sys

---

.github/workflows/coverage.yml
flake.nix

Fix the coverage computation: take out the previous action which has not been updated in two years. Instead, we follow the README[0] of the project to run directly.
[0]: https://github.com/xd009642/tarpaulin#github-actions

Fix coverage

---

fitsio/Cargo.toml

This branch fixes an invalid merge that was not caught in CI since the failing test was not included in the list of required checks.

Fix bad merge from dependabot

---

.github/workflows/schedule.yml
bin/test
flake.lock
flake.nix
rust-toolchain.toml

Fix the following output:
```
Checking fitsio v0.21.2 (/home/runner/work/rust-fitsio/rust-fitsio/fitsio)
error: usage of `Arc<T>` where `T` is not `Send` or `Sync`
--> fitsio/src/threadsafe_fitsfile.rs:37:28
|
37 |         ThreadsafeFitsFile(Arc::new(Mutex::new(self)))
|                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: consider using `Rc<T>` instead or wrapping `T` in a std::sync type like `Mutex<T>`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
= note: `#[deny(clippy::arc_with_non_send_sync)]` on by default
```
https://github.com/simonrw/rust-fitsio/actions/runs/5441703917/jobs/9895972197#step:5:704

Fix clippy lint about Arc<T>

---

fitsio/Cargo.toml

This fixes recent build errors with nightly as we have to configure a clippy feature specifically.
E.g. https://github.com/simonrw/rust-fitsio/actions/runs/8981350549

Add clippy feature

---

.github/workflows/release-plz.yml

Custom PATs must be used to allow GitHub to run actions on automated PRs

chore: use custom PAT for release-plz actions

---

.github/dependabot.yml
.github/workflows/check.yml
.github/workflows/coverage.yml
.github/workflows/schedule.yml
.github/workflows/test.yml

**Add groups to cargo package updates**
We only want one update PR (per crate) if multiple crates change
**Mark main tests to only run on code changes**
We don't need to run the full test suite on CI configuration changes

chore(deps): group updates and be more selective about CI runs

---

bin/test

It's nice to be able to see _all_ tests that fail, rather than failing on the first one. With the `bin/test` script.

chore: don't block on test failures

---

fitsio/src/errors.rs
fitsio/src/hdu.rs
fitsio/src/headers/mod.rs
fitsio/src/tables.rs

Fix a nightly clippy lint (e.g. https://github.com/simonrw/rust-fitsio/actions/runs/11312411340)

Allow needless-lifetimes

---

fitsio/src/fitsfile.rs
fitsio/src/longnam.rs

Include a method to access the file path of the `FitsFile`.
During my investigation I found that there was no reason to make it optional. Given this, I have made the field/function return non-optional as well.
Also: it is stored as a `PathBuf` internally, and inherently refers to a path on disk, so let's return a `Path` in that case.
Closes #366

feat: add `FitsFile::file_path` method to access `FitsFile` file path

---

README.md
fitsio-sys/CHANGELOG.md
fitsio-sys/Cargo.toml
fitsio/CHANGELOG.md
fitsio/Cargo.toml
fitsio/src/lib.rs

* `fitsio`: 0.21.5 -> 0.21.6 (✓ API compatible changes)
* `fitsio-sys`: 0.5.3 -> 0.5.4 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- add `FitsFile::file_path` method to access `FitsFile` file path ([#367](https://github.com/simonrw/rust-fitsio/pull/367))
- Allow needless-lifetimes ([#363](https://github.com/simonrw/rust-fitsio/pull/363))
</blockquote>
<blockquote>
- *(deps)* update bindgen requirement from 0.69 to 0.70 in /fitsio-sys in the cargo-packages group ([#357](https://github.com/simonrw/rust-fitsio/pull/357))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).

chore: release

---

bin/test
fitsio-sys/examples/print_version.rs
fitsio-sys/src/lib.rs
fitsio/src/lib.rs

We provide an example to print the cfitiso version.
Note: this is designed to work on versions 3+ so we don't support the semver patch version (yet).
We also add running this example before each test that uses features so that we can debug in the future cfitsio versions.

Include function to get cfitsio version

---

fitsio-sys/build.rs

While trying to add alternative Windows build mode, I couldn't help but notice that build.rs has a lot of duplicate code that could be better expressed through cfg branching.
I extracted it as such, so now each build step is defined only in one place.

Simplify build.rs of fitsio-sys

---

Dockerfile

Clippy is included by rustup per default and not needed, cf. https://doc.rust-lang.org/clippy/installation.html

#373 removing x86_64 toolchain dependency for clippy

---

.github/workflows/test.yml

It would be nice to run the CI tests in parallel, and separetely to get a better overview of what works and what doesn't.
Note: the CI is breaking for an unrelated reason on macos

Split out ci for test step
